Display/books
AlterTrap/book-management-fe pull request #1
Opened 2023-09-14 04:30 UTC by KhaiNd3

2023-09-14 06:59 UTC, HaiTT-DN commented on src/components/books/Index.js
> +        if (!name || name.trim() !== '') params.name = name;
Điều kiện if ở đây là "nếu name k đúng thì params.name = name"? Điều kiện chi lạ ri

2023-09-14 06:59 UTC, HaiTT-DN commented on src/components/books/Index.js
> +        if (!category || category.trim() !== '') params.category = category;
Tương tự

2023-09-14 07:11 UTC, laihuynhnhatminh commented on src/components/books/Index.js
> +        if (!name || name.trim() !== '') params.name = name;
if (name || name.trim('')) params.name = name
name.trim('') luôn trả về string, nếu trả về string là rỗng thì if trả về false thì không cần check !== '' nữa.

2023-09-14 07:13 UTC, laihuynhnhatminh requested changes
Please fix comment.

2023-09-14 13:56 UTC, KhaiNd3 commented on src/components/books/Index.js
> +        if (!name || name.trim() !== '') params.name = name;
đã fix lỗi

2023-09-14 14:05 UTC, HaiTT-DN approved these changes

2023-09-15 18:27 UTC, laihuynhnhatminh approved these changes
For now, it's ok to merge.
Will need to update and refactor later.

2023-09-16 08:28 UTC, SillyBoomer commented on src/components/books/Index.js
> +        res = await API.get('books', {});
@KhaiNd3 
Sửa lại chỉ cần gọi api 1 lần. 1 lần gọi xử lý cho cả lúc có name/category và lúc không có.

2023-09-16 08:28 UTC, SillyBoomer commented on src/components/books/Index.js
> +          res = null;
@KhaiNd3 
Tạo 1 biến chứa list, tuỳ thuộc vào kết quả của res/error mà gán giá trị cho phù hợp.
Sau đó truyền biến trên vào setList.
Không nên biến đổi giá trị của res.

TRong trường hợp gặp err, lấy error.response.status làm điều kiện xử lý, nếu 404 hiện không tìm thấy, nếu 500 thì hiện lỗi servẻ

2023-09-16 08:28 UTC, SillyBoomer commented on src/components/books/common/api.js
> +import axios from 'axios';
@KhaiNd3 
Common đưa ra bên ngoài, vì là common nên không thuộc thư mục của một entity cụ thể nào.

2023-09-16 08:28 UTC, SillyBoomer commented on src/components/books/common/list.js
> +        <p>No book found</p>
@KhaiNd3 
Việc hiển thị thông báo không tìm thấy/lỗi server đưa ra chỗ khác xử lý.
List chỉ có nhiệm vụ hiển thị danh sách item.
List.js này tuy nằm trong common, nhưng thiết kế chỉ để hiển thị book => sửa lại, hoặc tổng quát hoá rồi đưa ra common, hoặc chuyên biệt hoá và đưa nó thành 1 component của book.

2023-09-16 15:49 UTC, KhaiNd3 commented on src/components/books/Index.js
> +        res = await API.get('books', {});
đã fix

2023-09-16 15:50 UTC, KhaiNd3 commented on src/components/books/Index.js
> +          res = null;
đã fix

2023-09-16 15:50 UTC, KhaiNd3 commented on src/components/books/common/api.js
> +import axios from 'axios';
đã fix

2023-09-16 15:50 UTC, KhaiNd3 commented on src/components/books/common/list.js
> +        <p>No book found</p>
đã fix

2023-09-17 01:25 UTC, SillyBoomer commented on src/components/books/common/api.js
> +import axios from 'axios';
@KhaiNd3 
Đưa common ra ngoài tức là đưa cả thư mục common ra bên ngoài khỏi thư mục entity.

components
   |______ books
   |                    |______index.js
   |______common
   |                        |______error.js
   |                        |______api.js
   |______examples
                            |______ịndex.js

2023-09-17 01:32 UTC, SillyBoomer commented on src/components/books/Index.js
> +        }
@KhaiNd3 
Trong trong useEffect không xử lý hiển thị giao diện.
Ở đây chỉ gán thông báo lỗi dưới dạng string, việc hiển thị component nằm trong phần return.

```
const [error, setError] = useState('');
...

} catch (err) {
    if (err.response && err.response.status === 404) {
      setError(error.response.msg);
    }
  }
...
if (error) {
    return <Error msg={error} />;
}
```

Chưa có xử lý lỗi 500.

2023-09-17 06:20 UTC, KhaiNd3 commented on src/components/books/common/api.js
> +import axios from 'axios';
đã fix theo như cmt

2023-09-17 06:20 UTC, KhaiNd3 commented on src/components/books/Index.js
> +        }
đã fix theo như cmt và thêm điều kiện xử lý lỗi 500

2023-09-17 07:37 UTC, SillyBoomer commented on src/components/books/Index.js
> +        }
@KhaiNd3 
Nếu 404 và 500 đều cùng trả về err.response.statusText thì cần gì phải phân làm 2 trường hợp?
Tuỳ thuộc vào status code mình sẽ chủ động gắn thông báo lỗi cho phù hợp.
Giả sử mình gọi api từ bên khác như gg hay youtube thì sao?
Giả sử thông báo lỗi của các bên đấy không giống như mình  mong đợi thì sao?

Không nên lấy statusText từu err để hiển thị vì nó có thể không tường minh hoặc hiển thị các thông tin không mong muốn.

Nếu 404 => gắn thông báo book not found
Nếu 500 => gán thông báo internal server error, please try again later

2023-09-17 14:46 UTC, SillyBoomer approved these changes

2023-09-17 14:47 UTC, merged